[tool.poetry]
name = "goods_categorization_demo"
version = "0.1.0"
description = "Demo for automatic categorization of consumer goods with an arbitrary category tree"
authors = ["Andrey Vasnetsov <andrey@vasnetsov.com>"]

[tool.poetry.dependencies]
python = "~3.11"
fastapi = "^0.103.1"
uvicorn = "^0.18.3"
qdrant-client = { extras = ["fastembed"], version = "1.14.2" }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
